### ISSUE TITLE
Create an RMarkdown for 'title.akas' data

### ISSUE THREAD

**Issue by a-reyhan** [course-dprep/team-project-team-13#12]

**Comment by sjvangoor** [comment]
Hey! You can use this for some guidance on this part!

<img width="961" alt="Screenshot 2023-09-12 at 12 01 53" src="https://github.com/course-dprep/team-project-team-13/assets/143106831/f18c5ddf-c061-4de5-8102-b05ce37ab628">

**Comment by sjvangoor** [comment]
We have decided to leave this dataset out of the project as it's data is irrelevant for our research context.
